# Generated by Django 5.0.6 on 2025-04-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
