# Generated by Django 5.1.7 on 2025-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('full_description_image', models.ImageField(blank=True, upload_to='services/')),
                ('is_featured', models.BooleanField(default=False, help_text="Cocher pour afficher ce service en page d'accueil")),
                ('icon', models.CharField(blank=True, help_text='Utilisez les classes Font Awesome. Ex: code → fa-code', max_length=50)),
                ('header_image', models.ImageField(default='services/headers/default_header.jpg', upload_to='services/headers/')),
                ('strengths_image', models.ImageField(blank=True, upload_to='services/strengths/')),
                ('strengths_text', models.TextField(blank=True, default='Notre expertise dans ce domaine inclut :\n- Solution personnalisée\n- Technologie de pointe\n- Support premium', max_length=500, verbose_name='Atouts clés')),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (plus petit chiffre en premier)")),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
